#!/bin/bash
#       
#       Copyright 2012 John Francis Mukulu <john.f.mukulu@gmail.com>
#       Django CMS Deployer
#       Version 2.0
#       OS Target: Debian based Linux Distros
#
##################################
# Assumed project structure
# -projectdir
#   -__init__.py
#   -manage.py
#   -settings.py
#   -url.py
#   -media/
#   -deploy.sh
#
# PROJECT SETTINGS (Should be same as those in settings.py)
SITE_PREFIX="/djangoproject"		#To be accessed at http://localhost/djangoproject
MEDIA_URL="/media"					#To be accessed at http://localhost/media/
ADMIN_MEDIA_PREFIX="/static/admin/"	#To be accessed at http://localhost/static/admin/
MEDIA_ROOT=""						#Full path(Leave blank if follows assumed project structure)
DJANGO_VERSION="1.3.1"				#Version to be downloaded from http://www.djangoproject.com/download/

function __dir__() {
    # Deduce this file's full dir path
    FILE_PATH="$0"
    CURRENT_DIR="$PWD"
    DIR_NAME=$( dirname $FILE_PATH )
    reference="$(echo $FILE_PATH | cut --fields=1 --delimiter=$'/')"
    if [ -n "$reference" ];then
        if [  "$reference" == "." ];then
            dirpathwithperiod=$(dirname $FILE_PATH)
            if [  "$reference" == "./" ];then
				dirpathwithoutperiod=${dirpathwithperiod[@]/\.\//}
			else
				dirpathwithoutperiod=${dirpathwithperiod[@]/\./}
			fi
            fullpath="${CURRENT_DIR}${dirpathwithoutperiod}"
            echo "$fullpath"
        else
            dirpathwithperiod=$(dirname $FILE_PATH)
            fullpath="${CURRENT_DIR}/${dirpathwithperiod}"
            echo "$fullpath"
            
        fi
    else
        fullpath=$(dirname $FILE_PATH)
        echo "$fullpath"
    fi
}
PROJECT_DIR="$(__dir__)"
PROJECT_NAME="$( basename $(__dir__) )"
if [ -z "$MEDIA_ROOT" ];then # Takes care of MEDIA_ROOT if follows default standards
    MEDIA_ROOT="${PROJECT_DIR}/media"
fi

#Install Postgres & Mysql database server if it's not installed yet
#sudo apt-get install postgresql mysql-client mysql-server

# Install Dependencies
echo "====================================================="
echo "===========  Installing Dependencies   =============="
LastKnownLocation="$PWD"
sudo apt-get install python python-setuptools apache2 libapache2-mod-wsgi python-psycopg2 python-mysqldb python-sqlite python-imaging &&
echo "*  Downloading Django-${DJANGO_VERSION} ..." &&
# Install latest django
wget "http://www.djangoproject.com/download/${DJANGO_VERSION}/tarball/" -O /tmp/Django-1.3.1.tar.gz && echo "* Extracting Django..." &&
sudo tar -xvf /tmp/Django-1.3.1.tar.gz -C /tmp/ && echo "* Installin django..." &&
cd /tmp/Django-1.3.1 && sudo python setup.py install && cd "$LastKnownLocation" && echo "* Locating django location..."

# Configuring apache server to load the project:
ManuallyInstalledDjangoLocation2_7="/usr/local/lib/python2.7/dist-packages/django"
AptGetInstalledDjangoLocation2_7="/usr/lib/pymodules/python2.7/django"
ManuallyInstalledDjangoLocation2_6="/usr/local/lib/python2.6/dist-packages/django"
AptGetInstalledDjangoLocation2_6="/usr/lib/pymodules/python2.6/django"
if [ -d "$ManuallyInstalledDjangoLocation2_7" ];then
	DJANGO_LOCATION="$ManuallyInstalledDjangoLocation2_7"
	echo "Using Django Location:${DJANGO_LOCATION}"
elif [ -d "$AptGetInstalledDjangoLocation2_7" ];then
	DJANGO_LOCATION="$AptGetInstalledDjangoLocation2_7"
	echo "Using Django Location:${DJANGO_LOCATION}"
elif  [ -d "$ManuallyInstalledDjangoLocation2_6" ];then
	DJANGO_LOCATION="$ManuallyInstalledDjangoLocation2_6"
	echo "Using Django Location:${DJANGO_LOCATION}"
elif [ -d "$AptGetInstalledDjangoLocation2_6" ];then
	DJANGO_LOCATION="$AptGetInstalledDjangoLocation2_6"
	echo "Using Django Location:${DJANGO_LOCATION}"
else
	#zenity --warning --title="Django Installation Warning" --text="Could not get Location where django is installed"
	# Get the path from commandline
	echo -e '\E[;31m'"\033[1mPATH OF INSTALLED DJANGO NOT FOUND! \033[0m"
	echo -n "Enter it manually 'no backlash at the end', e.g. /usr/lib/pymodules/python2.6/django) :" && read DJANGO_LOCATION
	# Check if it's a py project
fi

# Create apache2 citywebsite laucher
echo "=========================================================="
sudo touch "${PROJECT_DIR}/${PROJECT_NAME}.wsgi"
sudo chmod a+rwx "${PROJECT_DIR}/${PROJECT_NAME}.wsgi"
#Updates wsgi script referred by apache
sudo echo "#!/usr/bin/env python
# -*- coding: utf-8 -*-
#       @AutoGenerated by deploy.sh
#       Copyright 2011 John Francis Mukulu <john.f.mukulu@gmail.com>
import os
import sys
PROJECT_DIR = os.path.dirname(__file__)
PROJECT_PARENT_DIR = os.path.dirname(PROJECT_DIR)

sys.path.append(PROJECT_DIR)
sys.path.append(PROJECT_PARENT_DIR)
import ${PROJECT_NAME}

os.environ['DJANGO_SETTINGS_MODULE'] = '${PROJECT_NAME}.settings'

import django.core.handlers.wsgi
application = django.core.handlers.wsgi.WSGIHandler()
" > "${PROJECT_DIR}/${PROJECT_NAME}.wsgi"

echo "* Setting up ${PROJECT_DIR}/${PROJECT_NAME}.wsgi"
echo "* Configuring $PROJECT_NAME into apache"
echo ""
#Writes apache configurations for the project
WSGI_FILE_NAME="$PROJECT_NAME"
APACHE2_CONFIG="/etc/apache2/conf.d"
WSGI_CONFIG_FILE="${APACHE2_CONFIG}/${WSGI_FILE_NAME}"
sudo touch ${WSGI_CONFIG_FILE}
sudo chmod a+rwx ${WSGI_CONFIG_FILE}
sudo echo "Alias ${ADMIN_MEDIA_PREFIX} \"${DJANGO_LOCATION}/contrib/admin/media/\"" > ${WSGI_CONFIG_FILE}
sudo echo "
Redirect /en${SITE_PREFIX} ${SITE_PREFIX}
<Directory \"${DJANGO_LOCATION}/contrib/admin/media\">
	Order deny,allow
	Allow from all
</Directory>" >> ${WSGI_CONFIG_FILE}
sudo echo "Alias ${MEDIA_URL} \"$MEDIA_ROOT\"" >> ${WSGI_CONFIG_FILE}
sudo echo "
<Directory \"$MEDIA_ROOT\">
	Order deny,allow
	Allow from all
</Directory>" >> ${WSGI_CONFIG_FILE}
echo "* Finished setting ${WSGI_CONFIG_FILE} in apache"
sudo echo "WSGIScriptAlias ${SITE_PREFIX} \"${PROJECT_DIR}/${PROJECT_NAME}.wsgi\"" >> ${WSGI_CONFIG_FILE}

sudo echo '
<Locationmatch "^/(robot.txt|favicon.ico)">
	SetHandler default
</Locationmatch>' >> ${WSGI_CONFIG_FILE}
echo "* Finished linking ${WSGI_CONFIG_FILE} with ${PROJECT_DIR}/${PROJECT_NAME}.wsgi"
echo "* Activating python-modwsgi"
sudo a2enmod wsgi
echo "* Restarting web server"
sudo service apache2 restart

# Setting up the database
echo "* Everything is done..."
echo "* ${PROJECT_NAME} is set running under http://localhost${SITE_PREFIX}"
exit 0
